language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic


before_install:
  - travis_retry ./.travis/setup.sh

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd root; source bin/thisroot.sh; cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd 6.14.02/ && export PATH=${PWD}/bin:${PATH} && source bin/thisroot.sh && export PYTHONPATH=${PWD}/lib:${PYTHONPATH} && echo ${PYTHONPATH} && cd ../; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 setup.py test && python3 -m pip install -e . && python3 -m pylint hepdata_lib/*.py; fi

after_success:
  - coveralls

